# Generated by Django 3.0.2 on 2020-01-31 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.ManyToManyField(help_text='Выберите язык вашей книги', to='catalog.Language'),
        ),
    ]
